### ISSUE TITLE
Crash when resolving path to local file - missing URI::encode

### ISSUE THREAD

**Issue by samnung** [epuber-io/epuber#71]
Ruby 2.7.0
Epuber 0.5.7

Solved issue, it was unicode character in path to file.

```
undefined method `encode' for URI:Module
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:213:in `rescue in resolved_link_to_file'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:209:in `resolved_link_to_file'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:355:in `rescue in block in resolve_resources_in'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:350:in `block in resolve_resources_in'
/usr/local/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/usr/local/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/usr/local/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.1-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:346:in `resolve_resources_in'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/xhtml_processor.rb:320:in `resolve_images'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/file_types/xhtml_file.rb:106:in `block in common_process'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/user_interface.rb:116:in `print_step_processing_time'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/file_types/xhtml_file.rb:105:in `common_process'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler/file_types/bade_file.rb:72:in `process'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:229:in `process_file'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:273:in `block in process_all_target_files'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:271:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:271:in `each_with_index'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:271:in `process_all_target_files'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:86:in `block in compile'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/vendor/globals_context.rb:14:in `catch'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/compiler.rb:73:in `compile'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/command/build.rb:90:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/command/build.rb:87:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/command/build.rb:87:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/lib/epuber/command.rb:29:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/epuber-0.5.7/bin/epuber:10:in `<top (required)>'
/usr/local/bin/epuber:23:in `load'
/usr/local/bin/epuber:23:in `<main>'
```

**Comment by samnung** [comment]
Solved in v0.6.0
